// TEMPORARY DATA

export let role = "admin";

export const propertiesData = [
  {
    id: 1,
    propertyId: "PROP123456",
    name: "Sunny Apartments",
    owner: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    location: "123 Main St, Anytown, USA",
    rent: "$1200/month",
    type: "2BHK Apartment",
    status: "Available",
    tenants: [],
  },
  {
    id: 2,
    propertyId: "PROP123457",
    name: "Cozy Cottage",
    owner: "Jane Smith",
    email: "jane@smith.com",
    photo:
      "https://images.pexels.com/photos/206172/pexels-photo-206172.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543210",
    location: "45 Elm St, Riverside, USA",
    rent: "$1800/month",
    type: "3BHK House",
    status: "Rented",
    tenants: ["Alice Brown"],
  },
  {
    id: 3,
    propertyId: "PROP123458",
    name: "Urban Heights",
    owner: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/323705/pexels-photo-323705.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "4567891230",
    location: "78 Park Ave, Downtown, USA",
    rent: "$2500/month",
    type: "4BHK Apartment",
    status: "Available",
    tenants: [],
  },
  {
    id: 4,
    propertyId: "PROP123459",
    name: "Serene Villas",
    owner: "Anna Santiago",
    email: "anna@santiago.com",
    photo:
      "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "3216549870",
    location: "12 Maple Dr, Suburbia, USA",
    rent: "$3500/month",
    type: "5BHK Villa",
    status: "Available",
    tenants: [],
  },
  {
    id: 5,
    propertyId: "PROP123460",
    name: "Lakeview Apartments",
    owner: "Jay French",
    email: "jay@french.com",
    photo:
      "https://images.pexels.com/photos/1643387/pexels-photo-1643387.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1597534862",
    location: "90 Lakeview Rd, Lakeside, USA",
    rent: "$2000/month",
    type: "3BHK Apartment",
    status: "Rented",
    tenants: ["Bob Green"],
  },
  {
    id: 6,
    propertyId: "PROP123461",
    name: "City Center Loft",
    owner: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/280229/pexels-photo-280229.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "7894561230",
    location: "120 Market St, City Center, USA",
    rent: "$2200/month",
    type: "1BHK Loft",
    status: "Available",
    tenants: [],
  },
  {
    id: 7,
    propertyId: "PROP123462",
    name: "Green Meadows",
    owner: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1643389/pexels-photo-1643389.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "6549873210",
    location: "35 Greenway Ln, Countryside, USA",
    rent: "$2800/month",
    type: "4BHK Townhouse",
    status: "Available",
    tenants: [],
  },
  {
    id: 8,
    propertyId: "PROP123463",
    name: "Hilltop Haven",
    owner: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1237894560",
    location: "50 Hilltop Rd, Highland, USA",
    rent: "$3200/month",
    type: "5BHK House",
    status: "Rented",
    tenants: ["Clara West"],
  },
  {
    id: 9,
    propertyId: "PROP123464",
    name: "Coastal Retreat",
    owner: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/210602/pexels-photo-210602.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9517538426",
    location: "80 Beachside Dr, Coastal City, USA",
    rent: "$4000/month",
    type: "Beach House",
    status: "Available",
    tenants: [],
  },
];

