// TEMPORARY DATA

export let role = "admin";

export const landlordsData = [
    {
      id: 1,
      landlordId: "9876543210",
      name: "Robert Smith",
      email: "robert@smith.com",
      photo:
        "https://images.pexels.com/photos/3182822/pexels-photo-3182822.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "9876543210",
      properties: ["Downtown Apartment", "Cozy Cottage"],
      address: "456 Elm St, Metropolis, USA",
    },
    {
      id: 2,
      landlordId: "9876543211",
      name: "Emily Johnson",
      email: "emily@johnson.com",
      photo:
        "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "9876543211",
      properties: ["Luxury Condo", "Suburban House"],
      address: "789 Oak St, Springfield, USA",
    },
    {
      id: 3,
      landlordId: "9876543212",
      name: "William Brown",
      email: "william@brown.com",
      photo:
        "https://images.pexels.com/photos/718261/pexels-photo-718261.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "9876543212",
      properties: ["Studio Apartment", "Beach Villa"],
      address: "321 Pine St, Rivertown, USA",
    },
    {
      id: 4,
      landlordId: "9876543213",
      name: "Sophia Davis",
      email: "sophia@davis.com",
      photo:
        "https://images.pexels.com/photos/1181414/pexels-photo-1181414.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "9876543213",
      properties: ["City Loft", "Mountain Cabin"],
      address: "654 Maple St, Highland, USA",
    },
    {
      id: 5,
      landlordId: "9876543214",
      name: "James Miller",
      email: "james@miller.com",
      photo:
        "https://images.pexels.com/photos/1680173/pexels-photo-1680173.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "9876543214",
      properties: ["Urban Duplex", "Countryside Retreat"],
      address: "987 Birch St, Greenfield, USA",
    },
    {
      id: 6,
      landlordId: "9876543215",
      name: "Olivia Wilson",
      email: "olivia@wilson.com",
      photo:
        "https://images.pexels.com/photos/2894297/pexels-photo-2894297.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "9876543215",
      properties: ["Lakefront Bungalow", "Suburban Duplex"],
      address: "111 Cedar St, Lakeside, USA",
    },
    {
      id: 7,
      landlordId: "9876543216",
      name: "Benjamin Moore",
      email: "benjamin@moore.com",
      photo:
        "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "9876543216",
      properties: ["Luxury Penthouse", "City Apartment"],
      address: "222 Ash St, Uptown, USA",
    },
    {
      id: 8,
      landlordId: "9876543217",
      name: "Isabella Taylor",
      email: "isabella@taylor.com",
      photo:
        "https://images.pexels.com/photos/3153201/pexels-photo-3153201.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "9876543217",
      properties: ["Modern Townhouse", "Historic Manor"],
      address: "333 Willow St, Oldtown, USA",
    },
    {
      id: 9,
      landlordId: "9876543218",
      name: "Michael White",
      email: "michael@white.com",
      photo:
        "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "9876543218",
      properties: ["Industrial Loft", "Farmhouse"],
      address: "444 Spruce St, Valleyview, USA",
    },
    {
      id: 10,
      landlordId: "9876543219",
      name: "Charlotte King",
      email: "charlotte@king.com",
      photo:
        "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "9876543219",
      properties: ["Garden Apartment", "Urban Studio"],
      address: "555 Cypress St, Midtown, USA",
    },
  ];
  

export const tenantsData = [
    {
      id: 1,
      tenantId: "TEN123456",
      name: "John Doe",
      email: "john.doe@example.com",
      photo:
        "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "1234567890",
      property: "Ocean View Apartment",
      address: "123 Seaside Blvd, Miami, FL",
      paymentHistory: [
        { month: "January", amount: 2000, status: "Paid" },
        { month: "February", amount: 2000, status: "Paid" },
      ],
      rentalAgreementStatus: "Active",
    },
    {
      id: 2,
      tenantId: "TEN789012",
      name: "Jane Doe",
      email: "jane.doe@example.com",
      photo:
        "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "1234567890",
      property: "Downtown Loft",
      address: "456 Main St, New York, NY",
      paymentHistory: [
        { month: "January", amount: 3500, status: "Paid" },
        { month: "February", amount: 3500, status: "Pending" },
      ],
      rentalAgreementStatus: "Active",
    },
    {
      id: 3,
      tenantId: "TEN345678",
      name: "Mike Geller",
      email: "mike.geller@example.com",
      photo:
        "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "1234567890",
      property: "Suburban House",
      address: "789 Pine St, Springfield, IL",
      paymentHistory: [
        { month: "January", amount: 1500, status: "Paid" },
        { month: "February", amount: 1500, status: "Paid" },
      ],
      rentalAgreementStatus: "Active",
    },
    {
      id: 4,
      tenantId: "TEN901234",
      name: "Jay French",
      email: "jay.french@example.com",
      photo:
        "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "1234567890",
      property: "Luxury Condo",
      address: "101 Palm Drive, Los Angeles, CA",
      paymentHistory: [
        { month: "January", amount: 5000, status: "Paid" },
        { month: "February", amount: 5000, status: "Pending" },
      ],
      rentalAgreementStatus: "Active",
    },
    {
      id: 5,
      tenantId: "TEN567890",
      name: "Jane Smith",
      email: "jane.smith@example.com",
      photo:
        "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "1234567890",
      property: "City Studio",
      address: "202 Central Ave, Boston, MA",
      paymentHistory: [
        { month: "January", amount: 1200, status: "Paid" },
        { month: "February", amount: 1200, status: "Paid" },
      ],
      rentalAgreementStatus: "Active",
    },
    {
      id: 6,
      tenantId: "TEN678901",
      name: "Anna Santiago",
      email: "anna.santiago@example.com",
      photo:
        "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "1234567890",
      property: "Lakefront Villa",
      address: "303 Lakeview Rd, Austin, TX",
      paymentHistory: [
        { month: "January", amount: 4000, status: "Paid" },
        { month: "February", amount: 4000, status: "Pending" },
      ],
      rentalAgreementStatus: "Active",
    },
    {
      id: 7,
      tenantId: "TEN890123",
      name: "Allen Black",
      email: "allen.black@example.com",
      photo:
        "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "1234567890",
      property: "Mountain Cabin",
      address: "404 Alpine St, Denver, CO",
      paymentHistory: [
        { month: "January", amount: 2500, status: "Paid" },
        { month: "February", amount: 2500, status: "Paid" },
      ],
      rentalAgreementStatus: "Active",
    },
    {
      id: 8,
      tenantId: "TEN234567",
      name: "Ophelia Castro",
      email: "ophelia.castro@example.com",
      photo:
        "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "1234567890",
      property: "Urban Penthouse",
      address: "505 Skyline Ave, Seattle, WA",
      paymentHistory: [
        { month: "January", amount: 8000, status: "Paid" },
        { month: "February", amount: 8000, status: "Pending" },
      ],
      rentalAgreementStatus: "Active",
    },
    {
      id: 9,
      tenantId: "TEN456789",
      name: "Derek Briggs",
      email: "derek.briggs@example.com",
      photo:
        "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "1234567890",
      property: "Countryside Cottage",
      address: "606 Meadow Ln, Nashville, TN",
      paymentHistory: [
        { month: "January", amount: 1800, status: "Paid" },
        { month: "February", amount: 1800, status: "Paid" },
      ],
      rentalAgreementStatus: "Active",
    },
    {
      id: 10,
      tenantId: "TEN789345",
      name: "John Glover",
      email: "john.glover@example.com",
      photo:
        "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
      phone: "1234567890",
      property: "Modern Duplex",
      address: "707 Grove St, Chicago, IL",
      paymentHistory: [
        { month: "January", amount: 3200, status: "Paid" },
        { month: "February", amount: 3200, status: "Pending" },
      ],
      rentalAgreementStatus: "Active",
    },
  ];

  
  export const propertyManagersData = [
    {
      id: 1,
      name: "John Doe",
      managedProperties: ["Ocean View Apartment"],
      email: "john.doe@propertymanager.com",
      phone: "1234567890",
      address: "123 Main St, Miami, FL",
    },
    {
      id: 2,
      name: "Jane Doe",
      managedProperties: ["Downtown Loft"],
      email: "jane.doe@propertymanager.com",
      phone: "1234567890",
      address: "456 Main St, New York, NY",
    },
    {
      id: 3,
      name: "Mike Geller",
      managedProperties: ["Suburban House"],
      email: "mike.geller@propertymanager.com",
      phone: "1234567890",
      address: "789 Pine St, Springfield, IL",
    },
    {
      id: 4,
      name: "Jay French",
      managedProperties: ["Luxury Condo", "Urban Penthouse"],
      email: "jay.french@propertymanager.com",
      phone: "1234567890",
      address: "101 Palm Drive, Los Angeles, CA",
    },
    {
      id: 5,
      name: "Jane Smith",
      managedProperties: ["City Studio"],
      email: "jane.smith@propertymanager.com",
      phone: "1234567890",
      address: "202 Central Ave, Boston, MA",
    },
    {
      id: 6,
      name: "Anna Santiago",
      managedProperties: ["Lakefront Villa"],
      email: "anna.santiago@propertymanager.com",
      phone: "1234567890",
      address: "303 Lakeview Rd, Austin, TX",
    },
    {
      id: 7,
      name: "Allen Black",
      managedProperties: ["Mountain Cabin", "Countryside Cottage"],
      email: "allen.black@propertymanager.com",
      phone: "1234567890",
      address: "404 Alpine St, Denver, CO",
    },
    {
      id: 8,
      name: "Ophelia Castro",
      managedProperties: ["Urban Penthouse"],
      email: "ophelia.castro@propertymanager.com",
      phone: "1234567890",
      address: "505 Skyline Ave, Seattle, WA",
    },
    {
      id: 9,
      name: "Derek Briggs",
      managedProperties: ["Countryside Cottage", "Modern Duplex"],
      email: "derek.briggs@propertymanager.com",
      phone: "1234567890",
      address: "606 Meadow Ln, Nashville, TN",
    },
    {
      id: 10,
      name: "John Glover",
      managedProperties: ["Modern Duplex"],
      email: "john.glover@propertymanager.com",
      phone: "1234567890",
      address: "707 Grove St, Chicago, IL",
    },
  ];
 
  export const propertyCategoriesData = [
    {
      id: 1,
      name: "Apartment",
      propertyManagers: ["John Doe", "Jane Smith"],
    },
    {
      id: 2,
      name: "House",
      propertyManagers: ["Mike Geller", "Jay French"],
    },
    {
      id: 3,
      name: "Condo",
      propertyManagers: ["Anna Santiago", "Ophelia Castro"],
    },
    {
      id: 4,
      name: "Loft",
      propertyManagers: ["Allen Black", "Derek Briggs"],
    },
    {
      id: 5,
      name: "Villa",
      propertyManagers: ["Lora French", "Sue Brady"],
    },
    {
      id: 6,
      name: "Cottage",
      propertyManagers: ["Harriet Alvarado", "Mayme Keller"],
    },
    {
      id: 7,
      name: "Penthouse",
      propertyManagers: ["Gertrude Roy", "Rosa Singleton"],
    },
    {
      id: 8,
      name: "Studio",
      propertyManagers: ["Effie Lynch", "Brett Flowers"],
    },
    {
      id: 9,
      name: "Townhouse",
      propertyManagers: ["Hannah Bowman", "Betty Obrien"],
    },
    {
      id: 10,
      name: "Farmhouse",
      propertyManagers: ["Alice Phelps", "Russell Davidson"],
    },
  ];

  export const propertyListingsData = [
    {
      id: 1,
      name: "Sunny Apartment 1B",
      capacity: 4, // Maximum number of tenants
      location: "Anytown, USA",
      price: 1500,
      propertyManager: "Joseph Padilla",
    },
    {
      id: 2,
      name: "Cozy House 2A",
      capacity: 6,
      location: "Oakland, USA",
      price: 2500,
      propertyManager: "Blake Joseph",
    },
    {
      id: 3,
      name: "Modern Condo 3C",
      capacity: 3,
      location: "San Francisco, USA",
      price: 2200,
      propertyManager: "Tom Bennett",
    },
    {
      id: 4,
      name: "Spacious Loft 4B",
      capacity: 5,
      location: "Los Angeles, USA",
      price: 2000,
      propertyManager: "Aaron Collins",
    },
    {
      id: 5,
      name: "Charming Villa 5A",
      capacity: 8,
      location: "Miami, USA",
      price: 3500,
      propertyManager: "Iva Frank",
    },
    {
      id: 6,
      name: "Luxury Condo 5B",
      capacity: 4,
      location: "New York, USA",
      price: 4000,
      propertyManager: "Leila Santos",
    },
    {
      id: 7,
      name: "Family Townhouse 7A",
      capacity: 6,
      location: "Chicago, USA",
      price: 2800,
      propertyManager: "Carrie Walton",
    },
    {
      id: 8,
      name: "Elegant Studio 6B",
      capacity: 2,
      location: "Seattle, USA",
      price: 1800,
      propertyManager: "Christopher Butler",
    },
    {
      id: 9,
      name: "Seaside Cottage 6C",
      capacity: 4,
      location: "Santa Monica, USA",
      price: 2100,
      propertyManager: "Marc Miller",
    },
    {
      id: 10,
      name: "Modern Penthouse 6D",
      capacity: 3,
      location: "Las Vegas, USA",
      price: 5000,
      propertyManager: "Ophelia Marsh",
    },
  ];

  export const rentalAgreementsData = [
    {
      id: 1,
      property: "Sunny Apartment 1B",
      tenant: "John Doe",
      landlord: "Joseph Padilla",
      leaseStartDate: "2024-01-01",
      leaseEndDate: "2025-01-01",
      rentAmount: 1500,
    },
    {
      id: 2,
      property: "Cozy House 2A",
      tenant: "Jane Smith",
      landlord: "Blake Joseph",
      leaseStartDate: "2024-02-01",
      leaseEndDate: "2025-02-01",
      rentAmount: 2500,
    },
    {
      id: 3,
      property: "Modern Condo 3C",
      tenant: "Mike Geller",
      landlord: "Tom Bennett",
      leaseStartDate: "2024-03-01",
      leaseEndDate: "2025-03-01",
      rentAmount: 2200,
    },
    {
      id: 4,
      property: "Spacious Loft 4B",
      tenant: "Sarah Connor",
      landlord: "Aaron Collins",
      leaseStartDate: "2024-04-01",
      leaseEndDate: "2025-04-01",
      rentAmount: 2000,
    },
    {
      id: 5,
      property: "Charming Villa 5A",
      tenant: "Emma Watson",
      landlord: "Iva Frank",
      leaseStartDate: "2024-05-01",
      leaseEndDate: "2025-05-01",
      rentAmount: 3500,
    },
    {
      id: 6,
      property: "Luxury Condo 5B",
      tenant: "James Smith",
      landlord: "Leila Santos",
      leaseStartDate: "2024-06-01",
      leaseEndDate: "2025-06-01",
      rentAmount: 4000,
    },
    {
      id: 7,
      property: "Family Townhouse 7A",
      tenant: "Rachel Green",
      landlord: "Carrie Walton",
      leaseStartDate: "2024-07-01",
      leaseEndDate: "2025-07-01",
      rentAmount: 2800,
    },
    {
      id: 8,
      property: "Elegant Studio 6B",
      tenant: "Ross Geller",
      landlord: "Christopher Butler",
      leaseStartDate: "2024-08-01",
      leaseEndDate: "2025-08-01",
      rentAmount: 1800,
    },
    {
      id: 9,
      property: "Seaside Cottage 6C",
      tenant: "Monica Geller",
      landlord: "Marc Miller",
      leaseStartDate: "2024-09-01",
      leaseEndDate: "2025-09-01",
      rentAmount: 2100,
    },
    {
      id: 10,
      property: "Modern Penthouse 6D",
      tenant: "Phoebe Buffay",
      landlord: "Ophelia Marsh",
      leaseStartDate: "2024-10-01",
      leaseEndDate: "2025-10-01",
      rentAmount: 5000,
    },
  ];
 
  export const propertyInspectionsData = [
    {
      id: 1,
      property: "Sunny Apartment 1B",
      inspector: "John Doe",
      date: "2025-01-01",
    },
    {
      id: 2,
      property: "Cozy House 2A",
      inspector: "Jane Smith",
      date: "2025-01-02",
    },
    {
      id: 3,
      property: "Modern Condo 3C",
      inspector: "Mike Geller",
      date: "2025-01-03",
    },
    {
      id: 4,
      property: "Spacious Loft 4B",
      inspector: "Sarah Connor",
      date: "2025-01-04",
    },
    {
      id: 5,
      property: "Charming Villa 5A",
      inspector: "Emma Watson",
      date: "2025-01-05",
    },
    {
      id: 6,
      property: "Luxury Condo 5B",
      inspector: "James Smith",
      date: "2025-01-06",
    },
    {
      id: 7,
      property: "Family Townhouse 7A",
      inspector: "Rachel Green",
      date: "2025-01-07",
    },
    {
      id: 8,
      property: "Elegant Studio 6B",
      inspector: "Ross Geller",
      date: "2025-01-08",
    },
    {
      id: 9,
      property: "Seaside Cottage 6C",
      inspector: "Monica Geller",
      date: "2025-01-09",
    },
    {
      id: 10,
      property: "Modern Penthouse 6D",
      inspector: "Phoebe Buffay",
      date: "2025-01-10",
    },
  ];
 
  export const propertyMaintenanceTasksData = [
    {
      id: 1,
      property: "Sunny Apartment 1A",
      task: "Fix leaking faucet",
      maintenanceStaff: "Anthony Boone",
      dueDate: "2025-01-01",
    },
    {
      id: 2,
      property: "Cozy House 2A",
      task: "Repair damaged door",
      maintenanceStaff: "Clifford Bowen",
      dueDate: "2025-01-01",
    },
    {
      id: 3,
      property: "Modern Condo 3C",
      task: "Clean air conditioning unit",
      maintenanceStaff: "Catherine Malone",
      dueDate: "2025-01-01",
    },
    {
      id: 4,
      property: "Spacious Loft 4B",
      task: "Replace broken window",
      maintenanceStaff: "Willie Medina",
      dueDate: "2025-01-01",
    },
    {
      id: 5,
      property: "Charming Villa 5A",
      task: "Check plumbing for leaks",
      maintenanceStaff: "Jose Ruiz",
      dueDate: "2025-01-01",
    },
    {
      id: 6,
      property: "Luxury Condo 5B",
      task: "Install new light fixtures",
      maintenanceStaff: "Katharine Owens",
      dueDate: "2025-01-01",
    },
    {
      id: 7,
      property: "Family Townhouse 7A",
      task: "Fix heating system",
      maintenanceStaff: "Shawn Norman",
      dueDate: "2025-01-01",
    },
    {
      id: 8,
      property: "Elegant Studio 6B",
      task: "Paint interior walls",
      maintenanceStaff: "Don Holloway",
      dueDate: "2025-01-01",
    },
    {
      id: 9,
      property: "Seaside Cottage 6C",
      task: "Inspect roof for damage",
      maintenanceStaff: "Franklin Gregory",
      dueDate: "2025-01-01",
    },
    {
      id: 10,
      property: "Modern Penthouse 6D",
      task: "Re-grout bathroom tiles",
      maintenanceStaff: "Danny Nguyen",
      dueDate: "2025-01-01",
    },
  ];
 
  export const propertyRentalTransactionsData = [
    {
      id: 1,
      property: "Sunny Apartment 1A",
      tenant: "Alice Johnson",
      landlord: "John Doe",
      date: "2025-01-01",
      type: "rental",
      rentAmount: 1200,
    },
    {
      id: 2,
      property: "Cozy House 2A",
      tenant: "Bob Smith",
      landlord: "John Doe",
      date: "2025-01-01",
      type: "rental",
      rentAmount: 1500,
    },
    {
      id: 3,
      property: "Modern Condo 3C",
      tenant: "Charlie Lee",
      landlord: "John Doe",
      date: "2025-01-01",
      type: "rental",
      rentAmount: 1800,
    },
    {
      id: 4,
      property: "Spacious Loft 4B",
      tenant: "Dana White",
      landlord: "John Doe",
      date: "2025-01-01",
      type: "rental",
      rentAmount: 2200,
    },
    {
      id: 5,
      property: "Charming Villa 5A",
      tenant: "Eve Black",
      landlord: "John Doe",
      date: "2025-01-01",
      type: "rental",
      rentAmount: 2500,
    },
    {
      id: 6,
      property: "Luxury Condo 5B",
      tenant: "Frank Green",
      landlord: "John Doe",
      date: "2025-01-01",
      type: "rental",
      rentAmount: 2700,
    },
    {
      id: 7,
      property: "Family Townhouse 7A",
      tenant: "Grace Blue",
      landlord: "John Doe",
      date: "2025-01-01",
      type: "rental",
      rentAmount: 3000,
    },
    {
      id: 8,
      property: "Elegant Studio 6B",
      tenant: "Hank Red",
      landlord: "John Doe",
      date: "2025-01-01",
      type: "rental",
      rentAmount: 1300,
    },
    {
      id: 9,
      property: "Seaside Cottage 6C",
      tenant: "Ivy Orange",
      landlord: "John Doe",
      date: "2025-01-01",
      type: "rental",
      rentAmount: 1800,
    },
    {
      id: 10,
      property: "Modern Penthouse 6D",
      tenant: "Jack Purple",
      landlord: "John Doe",
      date: "2025-01-01",
      type: "rental",
      rentAmount: 3500,
    },
  ];
    
  export const propertyViewingsData = [
    {
      id: 1,
      title: "Sunny Apartment 1A Viewing",
      class: "1A",
      date: "2025-01-01",
      startTime: "10:00",
      endTime: "11:00",
    },
    {
      id: 2,
      title: "Cozy House 2A Viewing",
      class: "2A",
      date: "2025-01-01",
      startTime: "10:00",
      endTime: "11:00",
    },
    {
      id: 3,
      title: "Modern Condo 3C Viewing",
      class: "3A",
      date: "2025-01-01",
      startTime: "10:00",
      endTime: "11:00",
    },
    {
      id: 4,
      title: "Spacious Loft 4B Viewing",
      class: "4A",
      date: "2025-01-01",
      startTime: "10:00",
      endTime: "11:00",
    },
    {
      id: 5,
      title: "Charming Villa 5A Viewing",
      class: "5A",
      date: "2025-01-01",
      startTime: "10:00",
      endTime: "11:00",
    },
    {
      id: 6,
      title: "Luxury Condo 5B Viewing",
      class: "1B",
      date: "2025-01-01",
      startTime: "10:00",
      endTime: "11:00",
    },
    {
      id: 7,
      title: "Family Townhouse 7A Viewing",
      class: "2B",
      date: "2025-01-01",
      startTime: "10:00",
      endTime: "11:00",
    },
    {
      id: 8,
      title: "Elegant Studio 6B Viewing",
      class: "3B",
      date: "2025-01-01",
      startTime: "10:00",
      endTime: "11:00",
    },
    {
      id: 9,
      title: "Seaside Cottage 6C Viewing",
      class: "4B",
      date: "2025-01-01",
      startTime: "10:00",
      endTime: "11:00",
    },
    {
      id: 10,
      title: "Modern Penthouse 6D Viewing",
      class: "5B",
      date: "2025-01-01",
      startTime: "10:00",
      endTime: "11:00",
    },
  ];
  
  export const rentalPropertyUpdatesData = [
    {
      id: 1,
      title: "New Offer for Sunny Apartment 1A",
      class: "1A",
      date: "2025-01-01",
    },
    {
      id: 2,
      title: "Price Drop for Cozy House 2A",
      class: "2A",
      date: "2025-01-01",
    },
    {
      id: 3,
      title: "Availability Update for Modern Condo 3C",
      class: "3A",
      date: "2025-01-01",
    },
    {
      id: 4,
      title: "New Features in Spacious Loft 4B",
      class: "4A",
      date: "2025-01-01",
    },
    {
      id: 5,
      title: "Newly Renovated Charming Villa 5A",
      class: "5A",
      date: "2025-01-01",
    },
    {
      id: 6,
      title: "Luxury Condo 5B Available for Immediate Move-In",
      class: "1B",
      date: "2025-01-01",
    },
    {
      id: 7,
      title: "Family Townhouse 7A Special Discount",
      class: "2B",
      date: "2025-01-01",
    },
    {
      id: 8,
      title: "Price Increase for Elegant Studio 6B",
      class: "3B",
      date: "2025-01-01",
    },
    {
      id: 9,
      title: "Seaside Cottage 6C Available for Long-Term Rent",
      class: "4B",
      date: "2025-01-01",
    },
    {
      id: 10,
      title: "Modern Penthouse 6D New Listing",
      class: "5B",
      date: "2025-01-01",
    },
  ];

  export const rentalPropertyViewingSchedule = [
    {
      title: "Sunny Apartment 1A Viewing",
      allDay: false,
      start: new Date(2024, 0, 1, 8, 0),
      end: new Date(2024, 0, 1, 8, 45),
    },
    {
      title: "Cozy House 2A Viewing",
      allDay: false,
      start: new Date(2025, 0, 1, 9, 0),
      end: new Date(2025, 0, 1, 9, 45),
    },
    {
      title: "Modern Condo 3C Viewing",
      allDay: false,
      start: new Date(2025, 0, 1, 10, 0),
      end: new Date(2025, 0, 1, 10, 45),
    },
    {
      title: "Spacious Loft 4B Viewing",
      allDay: false,
      start: new Date(2025, 0, 1, 11, 0),
      end: new Date(2025, 0, 1, 11, 45),
    },
    {
      title: "Charming Villa 5A Viewing",
      allDay: false,
      start: new Date(2025, 0, 1, 13, 0),
      end: new Date(2025, 0, 1, 13, 45),
    },
    {
      title: "Luxury Condo 5B Viewing",
      allDay: false,
      start: new Date(2025, 0, 1, 14, 0),
      end: new Date(2025, 0, 1, 14, 45),
    },
    {
      title: "Family Townhouse 7A Viewing",
      allDay: false,
      start: new Date(2025, 0, 2, 9, 0),
      end: new Date(2025, 0, 2, 9, 45),
    },
    {
      title: "Elegant Studio 6B Viewing",
      allDay: false,
      start: new Date(2025, 0, 2, 10, 0),
      end: new Date(2025, 0, 2, 10, 45),
    },
    {
      title: "Seaside Cottage 6C Viewing",
      allDay: false,
      start: new Date(2025, 0, 2, 11, 0),
      end: new Date(2025, 0, 2, 11, 45),
    },
    {
      title: "Penthouse 6D Viewing",
      allDay: false,
      start: new Date(2025, 0, 2, 13, 0),
      end: new Date(2025, 0, 2, 13, 45),
    },
    {
      title: "Sunny Apartment 1A Viewing",
      allDay: false,
      start: new Date(2025, 0, 3, 8, 0),
      end: new Date(2025, 0, 3, 8, 45),
    },
    {
      title: "Cozy House 2A Viewing",
      allDay: false,
      start: new Date(2025, 0, 3, 9, 0),
      end: new Date(2025, 0, 3, 9, 45),
    },
    {
      title: "Modern Condo 3C Viewing",
      allDay: false,
      start: new Date(2025, 0, 3, 10, 0),
      end: new Date(2025, 0, 3, 10, 45),
    },
    {
      title: "Spacious Loft 4B Viewing",
      allDay: false,
      start: new Date(2025, 0, 3, 11, 0),
      end: new Date(2025, 0, 3, 11, 45),
    },
    {
      title: "Charming Villa 5A Viewing",
      allDay: false,
      start: new Date(2025, 0, 3, 13, 0),
      end: new Date(2025, 0, 3, 13, 45),
    },
    {
      title: "Luxury Condo 5B Viewing",
      allDay: false,
      start: new Date(2025, 0, 3, 14, 0),
      end: new Date(2025, 0, 3, 14, 45),
    },
    {
      title: "Family Townhouse 7A Viewing",
      allDay: false,
      start: new Date(2024, 7, 16, 14, 0),
    end: new Date(2024, 7, 16, 14, 45),
    },
  ];
    